### ISSUE TITLE
cooper software meeting

### ISSUE THREAD

**Issue by portellikurt** [kryptonmlt/team14#3]
Hey guys, I am writing here cause I don't have your emails/facebook :p cooper software sent me an email to ask us if we want to visit their office on November 10, 15:00 ?

**Comment by rachelclare47** [comment]
hiya,  if I can get a shift swap at work that would probably be fine for me :)

**Comment by toinsson** [comment]
i'll keep you posted !

**Comment by portellikurt** [comment]
hey guys he just asked me again if we are still attending .. its at 3 on thursday ? i will ask him if he is providing transport etc..

**Comment by rachelclare47** [comment]
hiya, unfortunately I can't get Thursday off work so I won't make it. hope
you have great time!

**Comment by portellikurt** [comment]
if you have another date in mind I can tell him another date maybe ?

**Comment by rachelclare47** [comment]
don't worry about it, I've got loads on at the moment so not really sure
when I'll be free - don't want to delay you til after exams!
